# Generated by Django 5.0.8 on 2024-08-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_wishlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wishlist_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
