# Generated by Django 5.0.8 on 2024-08-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_wishlist_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wishlist_count',
        ),
    ]
