# Generated by Django 5.0.8 on 2024-08-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_wishlist_count_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wishlist_added_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
