# Generated by Django 5.0.8 on 2024-09-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_discount_percentage_product_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default='999', max_digits=10, null=True),
        ),
    ]
