# Generated by Django 5.0.8 on 2024-09-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_disc_added',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
