# Generated by Django 5.0.8 on 2024-09-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_cat_disc_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ordered_times',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
