# Generated by Django 5.0.8 on 2024-09-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_product_ordered_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ordered_times',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
