# Generated by Django 5.0.8 on 2024-09-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_product_ordered_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ordered_times',
        ),
        migrations.AddField(
            model_name='product',
            name='ordered_times_size_large',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='ordered_times_size_medium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='ordered_times_size_small',
            field=models.IntegerField(default=0),
        ),
    ]
