# Generated by Django 5.0.8 on 2024-09-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_product_ordered_times_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ordered_times_size_large',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ordered_times_size_medium',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ordered_times_size_small',
        ),
        migrations.AddField(
            model_name='product',
            name='ordered_times',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
