# Generated by Django 5.0.8 on 2024-09-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_product_ordered_times_size_large_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ordered_times',
        ),
    ]
