# Generated by Django 5.0.8 on 2024-08-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_checkoutdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetails',
            name='coupon_applied',
            field=models.BooleanField(null=True),
        ),
    ]
