# Generated by Django 5.0.8 on 2024-08-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_checkoutdetails_coupon_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetails',
            name='coupon_applied',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
