# Generated by Django 5.0.8 on 2024-08-28 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_alter_checkoutdetails_coupon_applied'),
        ('orders', '0006_remove_order_coupon_remove_order_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetails',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.coupon'),
        ),
    ]
