# Generated by Django 5.0.8 on 2024-08-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_checkoutdetails_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetails',
            name='razorpay_key_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checkoutdetails',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
