# Generated by Django 5.0.8 on 2024-09-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_checkoutdetails_razorpay_key_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetails',
            name='before_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
