# Generated by Django 5.0.8 on 2024-09-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_checkoutdetails_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutdetails',
            name='cart',
        ),
    ]
