# Generated by Django 5.0.8 on 2024-09-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_checkoutdetails_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
