# Generated by Django 5.0.8 on 2024-09-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0011_cartitem_total_cartitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total',
        ),
    ]
