# Generated by Django 5.0.8 on 2024-09-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_remove_cartitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetails',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
