# Generated by Django 5.0.8 on 2024-09-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0015_alter_checkoutdetails_shipping_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetails',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10, null=True),
        ),
    ]
