# Generated by Django 5.0.8 on 2024-09-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0016_alter_checkoutdetails_shipping_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetails',
            name='coupon_applied',
            field=models.BooleanField(default=False, null=True, verbose_name='Applied'),
        ),
    ]
