# Generated by Django 5.0.8 on 2024-09-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='checked',
            field=models.BooleanField(null=True),
        ),
    ]
