# Generated by Django 5.0.8 on 2024-09-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='checked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
