# Generated by Django 5.0.8 on 2024-09-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer_added',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
