# Generated by Django 5.0.8 on 2024-09-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_offer_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='offer_added',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
