# Generated by Django 5.0.8 on 2024-08-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Coupon Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount Percentage')),
                ('minimum_purchase_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Purchase Amount')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='inactive', max_length=10, verbose_name='Status')),
                ('action', models.CharField(choices=[('block', 'Block'), ('unblock', 'Unblock')], default='unblock', max_length=10, verbose_name='Action')),
            ],
        ),
    ]
