# Generated by Django 5.0.8 on 2024-08-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_coupon_order_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
    ]
