# Generated by Django 5.0.8 on 2024-08-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_coupon_remove_order_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Quantity'),
        ),
    ]
