# Generated by Django 5.0.8 on 2024-09-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
