# Generated by Django 5.0.8 on 2024-09-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_after_price_order_before_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='after_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='before_price',
        ),
    ]
