# Generated by Django 5.0.8 on 2024-09-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_order_after_price_remove_order_before_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
