# Generated by Django 5.0.8 on 2024-09-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_coupon_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
