# Generated by Django 5.0.8 on 2024-09-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_ordereditems_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditems',
            name='total',
        ),
    ]
