# Generated by Django 5.0.8 on 2024-09-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_order_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10, null=True),
        ),
    ]
