# Generated by Django 5.0.8 on 2024-09-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_ordereditems_shipping_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return Pending', 'Return Pending'), ('Return Cancelled', 'Return Cancelled'), ('Return Success', 'Return Success'), ('Payment Pending', 'Payment Pending')], default='Pending', max_length=20, null=True),
        ),
    ]
