# Generated by Django 5.0.8 on 2024-09-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_redeemable_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Max Redeemable Value'),
        ),
    ]
