# Generated by Django 5.0.8 on 2024-09-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_order_address_line1_order_address_line2_order_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zip_code',
            new_name='pincode',
        ),
    ]
