# Generated by Django 5.0.8 on 2024-09-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_rename_zip_code_order_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applied',
            field=models.BooleanField(default=False, null=True, verbose_name='Applied'),
        ),
    ]
