# Generated by Django 5.0.8 on 2024-09-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_coupon_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='applied',
        ),
    ]
