# Generated by Django 5.0.8 on 2024-09-17 19:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_remove_coupon_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for the referral offer.', max_length=50, unique=True)),
                ('description', models.TextField(help_text='Description of the referral offer.')),
                ('reward_amount', models.DecimalField(decimal_places=2, help_text='Amount of reward for the referral.', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the offer is currently active.')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Start date of the offer.')),
                ('end_date', models.DateTimeField(blank=True, help_text='End date of the offer.', null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of times the offer can be used.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the offer was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the offer was last updated.')),
            ],
            options={
                'verbose_name': 'Referral Offer',
                'verbose_name_plural': 'Referral Offers',
                'ordering': ['-start_date'],
            },
        ),
    ]
