# Generated by Django 5.0.8 on 2024-09-17 19:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_referraloffer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referraloffer',
            name='description',
            field=models.TextField(help_text='Description of the referral offer.', null=True),
        ),
        migrations.AlterField(
            model_name='referraloffer',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Start date of the offer.', null=True),
        ),
    ]
