# Generated by Django 5.0.8 on 2024-09-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_order_coupon_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon_applied',
        ),
    ]
