# Generated by Django 5.0.8 on 2024-09-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_order_coupon_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon_id',
        ),
    ]
