# Generated by Django 5.0.8 on 2024-09-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_alter_order_coupon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
